
import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.RandomAccessFile;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDialog;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author manuel
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    int conta_universal;
    String universo_universal = "";

    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jd_menuCreacion = new javax.swing.JDialog();
        jLabel4 = new javax.swing.JLabel();
        bt_crearARLF = new javax.swing.JButton();
        bt_crearARLV = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jd_crearARLF = new javax.swing.JDialog();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        tf_nombreARLF1 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        js_campoR1 = new javax.swing.JSpinner();
        js_caracteresC1 = new javax.swing.JSpinner();
        bt_crearArchivo1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jd_nombrarCampos = new javax.swing.JDialog();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        tf_nombreHeader = new javax.swing.JTextField();
        bt_nombrarHeader = new javax.swing.JButton();
        bt_guardarHeader = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jd_menuAdministracion = new javax.swing.JDialog();
        jLabel13 = new javax.swing.JLabel();
        bt_adARLF = new javax.swing.JButton();
        bt_adARLV = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jd_addRegistro = new javax.swing.JDialog();
        jLabel15 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jt_addRegistroARLF = new javax.swing.JTable();
        BT_ADDREGISTROARLF = new javax.swing.JButton();
        bt_fileChooser = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        ppm_ARLF = new javax.swing.JPopupMenu();
        jmi_eliminar = new javax.swing.JMenuItem();
        jm_modificar = new javax.swing.JMenuItem();
        jd_crearARLV = new javax.swing.JDialog();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        tf_nombreARLV = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        BT_CREARALRV = new javax.swing.JButton();
        cb_adminRegistros = new javax.swing.JComboBox();
        cb_adminCampos = new javax.swing.JComboBox();
        jd_nombrarCampos2 = new javax.swing.JDialog();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        tf_nombreHeader2 = new javax.swing.JTextField();
        bt_crearHeader2 = new javax.swing.JButton();
        bt_saveHeader = new javax.swing.JButton();
        mostrar = new javax.swing.JDialog();
        jScrollPane4 = new javax.swing.JScrollPane();
        jt_addRegistroARLV = new javax.swing.JTable();
        jLabel23 = new javax.swing.JLabel();
        bt_fileChooserARLV = new javax.swing.JButton();
        BT_ADDREGISTROARLV = new javax.swing.JButton();
        bt_crearArchivos = new javax.swing.JButton();
        bt_adminArchivos = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        jd_menuCreacion.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        jLabel4.setForeground(java.awt.Color.red);
        jLabel4.setText("Creacion de Archivos");
        jd_menuCreacion.getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, -1, -1));

        bt_crearARLF.setText("Archivo de Longitud Fija");
        bt_crearARLF.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_crearARLFMouseClicked(evt);
            }
        });
        jd_menuCreacion.getContentPane().add(bt_crearARLF, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 80, 260, 80));

        bt_crearARLV.setText("Archivo de Longitud Varable");
        bt_crearARLV.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_crearARLVMouseClicked(evt);
            }
        });
        jd_menuCreacion.getContentPane().add(bt_crearARLV, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 200, 260, 80));
        jd_menuCreacion.getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 630, 370));

        jd_crearARLF.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        jLabel6.setForeground(java.awt.Color.red);
        jLabel6.setText("Archivo de Longitud Fija");
        jd_crearARLF.getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, -1, -1));

        jLabel7.setForeground(java.awt.Color.red);
        jLabel7.setText("Nombre del Archivo");
        jd_crearARLF.getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, -1, -1));
        jd_crearARLF.getContentPane().add(tf_nombreARLF1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 90, 250, -1));

        jLabel8.setForeground(java.awt.Color.red);
        jLabel8.setText("Campos/Registro");
        jd_crearARLF.getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 190, -1, -1));

        jLabel9.setForeground(java.awt.Color.red);
        jLabel9.setText("Caracteres/Campo");
        jd_crearARLF.getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 260, -1, -1));
        jd_crearARLF.getContentPane().add(js_campoR1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 190, -1, -1));
        jd_crearARLF.getContentPane().add(js_caracteresC1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 260, -1, -1));

        bt_crearArchivo1.setText("Crear Archivo");
        bt_crearArchivo1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_crearArchivo1MouseClicked(evt);
            }
        });
        jd_crearARLF.getContentPane().add(bt_crearArchivo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 200, 140, 60));
        jd_crearARLF.getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 610, 360));

        jd_nombrarCampos.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setForeground(java.awt.Color.red);
        jLabel11.setText("Nombrar Campos");
        jd_nombrarCampos.getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 20, -1, -1));

        jLabel12.setForeground(java.awt.Color.red);
        jLabel12.setText("Nombre");
        jd_nombrarCampos.getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, -1, -1));
        jd_nombrarCampos.getContentPane().add(tf_nombreHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 70, 170, -1));

        bt_nombrarHeader.setText("Nombrar Campo");
        bt_nombrarHeader.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_nombrarHeaderMouseClicked(evt);
            }
        });
        jd_nombrarCampos.getContentPane().add(bt_nombrarHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, 150, -1));

        bt_guardarHeader.setText("Guardar Cambios");
        bt_guardarHeader.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_guardarHeaderMouseClicked(evt);
            }
        });
        jd_nombrarCampos.getContentPane().add(bt_guardarHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 140, 150, -1));
        jd_nombrarCampos.getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 490, 250));

        jd_menuAdministracion.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        jLabel13.setForeground(java.awt.Color.red);
        jLabel13.setText("Menu Administracion");
        jd_menuAdministracion.getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 30, 240, 30));

        bt_adARLF.setText("Administracion ARLF");
        bt_adARLF.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_adARLFMouseClicked(evt);
            }
        });
        jd_menuAdministracion.getContentPane().add(bt_adARLF, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 80, 160, 70));

        bt_adARLV.setText("Administracion ARLV");
        bt_adARLV.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_adARLVMouseClicked(evt);
            }
        });
        jd_menuAdministracion.getContentPane().add(bt_adARLV, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 170, 160, 70));
        jd_menuAdministracion.getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 480, 300));

        jd_addRegistro.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        jLabel15.setForeground(java.awt.Color.red);
        jLabel15.setText("Administracion ARLF");
        jd_addRegistro.getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 20, 250, -1));

        jt_addRegistroARLF.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jt_addRegistroARLF.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jt_addRegistroARLFMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jt_addRegistroARLF);

        jd_addRegistro.getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 70, -1, 110));

        BT_ADDREGISTROARLF.setText("Agregar Registro");
        BT_ADDREGISTROARLF.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BT_ADDREGISTROARLFMouseClicked(evt);
            }
        });
        jd_addRegistro.getContentPane().add(BT_ADDREGISTROARLF, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 210, 130, -1));

        bt_fileChooser.setText("Seleccionar Archivo");
        bt_fileChooser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_fileChooserMouseClicked(evt);
            }
        });
        jd_addRegistro.getContentPane().add(bt_fileChooser, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 210, -1, -1));
        jd_addRegistro.getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, 350));

        jmi_eliminar.setText("Eliminar Registro");
        jmi_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_eliminarActionPerformed(evt);
            }
        });
        ppm_ARLF.add(jmi_eliminar);
        jmi_eliminar.getAccessibleContext().setAccessibleName("Eliminar");

        jm_modificar.setText("jMenuItem1");
        jm_modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jm_modificarActionPerformed(evt);
            }
        });
        ppm_ARLF.add(jm_modificar);

        jd_crearARLV.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel17.setText("Archivos de Longitud Variable");
        jd_crearARLV.getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, -1, -1));

        jLabel18.setText("Nombre");
        jd_crearARLV.getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 70, -1, -1));
        jd_crearARLV.getContentPane().add(tf_nombreARLV, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 60, 160, -1));

        jLabel19.setText("Administracion Registros");
        jd_crearARLV.getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, -1, -1));

        jLabel20.setText("Administracion Campos");
        jd_crearARLV.getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 140, -1, -1));

        BT_CREARALRV.setText("Crear");
        BT_CREARALRV.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BT_CREARALRVMouseClicked(evt);
            }
        });
        jd_crearARLV.getContentPane().add(BT_CREARALRV, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 50, 70, -1));

        cb_adminRegistros.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Indicador Longitud", "Delimitadores", "Tabla Indice" }));
        jd_crearARLV.getContentPane().add(cb_adminRegistros, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, 180, 30));

        cb_adminCampos.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Indicador Longitud", "Delimitadores", "Key Value" }));
        jd_crearARLV.getContentPane().add(cb_adminCampos, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 170, 180, 30));

        jd_nombrarCampos2.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel21.setText("Nombrar Campos");
        jd_nombrarCampos2.getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, 130, -1));

        jLabel22.setText("Nombre");
        jd_nombrarCampos2.getContentPane().add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, -1, -1));
        jd_nombrarCampos2.getContentPane().add(tf_nombreHeader2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 70, 190, -1));

        bt_crearHeader2.setText("Nombrar");
        bt_crearHeader2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_crearHeader2MouseClicked(evt);
            }
        });
        jd_nombrarCampos2.getContentPane().add(bt_crearHeader2, new org.netbeans.lib.awtextra.AbsoluteConstraints(104, 120, 110, -1));

        bt_saveHeader.setText("Guardar Campos");
        bt_saveHeader.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_saveHeaderMouseClicked(evt);
            }
        });
        jd_nombrarCampos2.getContentPane().add(bt_saveHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 120, -1, -1));

        mostrar.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jt_addRegistroARLV.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jt_addRegistroARLV.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jt_addRegistroARLVMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(jt_addRegistroARLV);

        mostrar.getContentPane().add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 70, -1, 110));

        jLabel23.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        jLabel23.setForeground(java.awt.Color.red);
        jLabel23.setText("Administracion ARLV");
        mostrar.getContentPane().add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 20, 250, -1));

        bt_fileChooserARLV.setText("Seleccionar Archivo");
        bt_fileChooserARLV.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_fileChooserARLVMouseClicked(evt);
            }
        });
        mostrar.getContentPane().add(bt_fileChooserARLV, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 210, -1, -1));

        BT_ADDREGISTROARLV.setText("Agregar Registro");
        BT_ADDREGISTROARLV.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BT_ADDREGISTROARLVMouseClicked(evt);
            }
        });
        mostrar.getContentPane().add(BT_ADDREGISTROARLV, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 210, 130, -1));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bt_crearArchivos.setText("Creacion de Archivos");
        bt_crearArchivos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_crearArchivosMouseClicked(evt);
            }
        });
        getContentPane().add(bt_crearArchivos, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 80, 240, 90));

        bt_adminArchivos.setText("Administracion de Archivos");
        bt_adminArchivos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_adminArchivosMouseClicked(evt);
            }
        });
        getContentPane().add(bt_adminArchivos, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 200, 240, 90));

        jLabel2.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        jLabel2.setForeground(java.awt.Color.red);
        jLabel2.setText("Oracle");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 20, -1, -1));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 680, 380));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_crearArchivosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_crearArchivosMouseClicked
        this.showDialog(this.jd_menuCreacion);
    }//GEN-LAST:event_bt_crearArchivosMouseClicked

    private void bt_crearARLFMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_crearARLFMouseClicked
        this.jd_menuCreacion.setVisible(false);
        this.showDialog(jd_crearARLF);
    }//GEN-LAST:event_bt_crearARLFMouseClicked

    private void bt_crearArchivo1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_crearArchivo1MouseClicked
        nombreArchivo = this.tf_nombreARLF1.getText();
        camposPorRegistro = Integer.parseInt(this.js_campoR1.getValue() + "");
        caracteresPorCampo = Integer.parseInt(this.js_caracteresC1.getValue() + "");
        archivoFijo = new ARLF(nombreArchivo, camposPorRegistro, caracteresPorCampo);
        this.tf_nombreARLF1.setText("");
        this.js_campoR1.setValue(0);
        this.js_caracteresC1.setValue(0);
        JOptionPane.showMessageDialog(this, "Su archivo ha sido creado exitosamente!!");
        this.jd_crearARLF.setVisible(false);
        this.showDialog(this.jd_nombrarCampos);
    }//GEN-LAST:event_bt_crearArchivo1MouseClicked

    private void bt_nombrarHeaderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_nombrarHeaderMouseClicked
        if (contador < camposPorRegistro) {
            header1 += this.tf_nombreHeader.getText() + "?";
            contador++;
            this.tf_nombreHeader.setText("");
            JOptionPane.showMessageDialog(this, "Campo nombrado correctamente");
        } else {
            this.tf_nombreHeader.setText("");
            JOptionPane.showMessageDialog(this, "Usted ya ha excedido el numero de campos", "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_bt_nombrarHeaderMouseClicked

    private void bt_guardarHeaderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_guardarHeaderMouseClicked
        if (contador == camposPorRegistro) {
            archivoFijo.addRegistro(header1);
            camposPorRegistro = 0;
            caracteresPorCampo = 0;
            contador = 0;
            JOptionPane.showMessageDialog(this, "Campos nombrados exitosamente!!");
        } else {
            JOptionPane.showMessageDialog(this, "Aun le faltan campos por nombrar", "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_bt_guardarHeaderMouseClicked

    private void bt_adminArchivosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_adminArchivosMouseClicked
        this.showDialog(this.jd_menuAdministracion);
    }//GEN-LAST:event_bt_adminArchivosMouseClicked

    private void bt_adARLFMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_adARLFMouseClicked
        this.jd_menuAdministracion.setVisible(false);
        this.showDialog(this.jd_addRegistro);
    }//GEN-LAST:event_bt_adARLFMouseClicked

    private void bt_fileChooserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_fileChooserMouseClicked
        JFileChooser fileChooser = new JFileChooser();
        int returnValue = fileChooser.showOpenDialog(this);
        String nombre = "";
        int posicion = 0;

        if (returnValue == JFileChooser.APPROVE_OPTION) {
            File file = fileChooser.getSelectedFile();
            nombre = file.getName();
            archivoFijo = new ARLF(file.getName());
        }

        DefaultTableModel modelo = new DefaultTableModel();
        String[] header = new String[fijo];
        String registroUnido = "";

        try {
            header = enviar_nombres(nombre);
            for (int i = 0; i < header.length; i++) {
                modelo.addColumn(header[i]);
            }
        } catch (IOException ex) {
            System.out.println("Metodo Fiallos");
        }
        try {
            modelo = archivoFijo.listar(modelo, sizeCampo, amountCampos);
        } catch (IOException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.jt_addRegistroARLF.setModel(modelo);
        fijo = header.length;
    }//GEN-LAST:event_bt_fileChooserMouseClicked

    private void BT_ADDREGISTROARLFMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BT_ADDREGISTROARLFMouseClicked
        String[] registro = new String[fijo];
        String registroCompactado = "";
        for (int i = 0; i < fijo; i++) {
            boolean seguir = true;
            while (seguir) {
                registro[i] = JOptionPane.showInputDialog("Ingrese un registro para su columna #" + i);
                if (registro[i].length() > sizeCampo) {
                    JOptionPane.showMessageDialog(this, "El tamaño del campo es demasiado grande");
                } else if (registro[0].length() == 0) {
                    JOptionPane.showMessageDialog(this, "Su llave primaria no puede estar vacia");
                } else if (registro[i].length() < sizeCampo) {
                    for (int j = registro[i].length(); j < sizeCampo; j++) {
                        registro[i] += "_";
                    }
                    seguir = false;
                } else {
                    seguir = false;
                }
            }
        }

        DefaultTableModel modelo = new DefaultTableModel();
        modelo = (DefaultTableModel) this.jt_addRegistroARLF.getModel();

        while (modelo.getRowCount() > 0) {
            modelo.removeRow(0);
        }

        for (int i = 0; i < registro.length; i++) {
            registroCompactado += registro[i];
        }
        try {
            archivoFijo.addCampo(registroCompactado, sizeCampo, amountCampos);
        } catch (IOException ex) {
            System.out.println("Metodo fiallos2");
        }
        try {
            modelo = archivoFijo.listar(modelo, sizeCampo, amountCampos);
        } catch (IOException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.jt_addRegistroARLF.setModel(modelo);
    }//GEN-LAST:event_BT_ADDREGISTROARLFMouseClicked

    private void jt_addRegistroARLFMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jt_addRegistroARLFMouseClicked
        if (evt.isMetaDown()) {
            this.ppm_ARLF.show(evt.getComponent(), evt.getX(), evt.getY());
        }
    }//GEN-LAST:event_jt_addRegistroARLFMouseClicked

    private void jmi_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_eliminarActionPerformed
        archivoFijo.eliminar(this.jt_addRegistroARLF.getSelectedRow() + 1);

        DefaultTableModel modelo = new DefaultTableModel();
        modelo = (DefaultTableModel) this.jt_addRegistroARLF.getModel();
        while (modelo.getRowCount() > 0) {
            modelo.removeRow(0);
        }

        try {
            modelo = archivoFijo.listar(modelo, sizeCampo, amountCampos);
        } catch (IOException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.jt_addRegistroARLF.setModel(modelo);
    }//GEN-LAST:event_jmi_eliminarActionPerformed

    private void jm_modificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jm_modificarActionPerformed
        String[] registro = new String[this.jt_addRegistroARLF.getColumnCount()];
        String nuevoRegistro = "";
        boolean seguir = true;
        int x = this.jt_addRegistroARLF.getSelectedRow();
        int y = this.jt_addRegistroARLF.getSelectedColumn();
        archivoFijo.eliminar(x + 1);

        for (int i = 0; i < this.jt_addRegistroARLF.getColumnCount(); i++) {
            registro[i] = this.jt_addRegistroARLF.getValueAt(x, i).toString();
        }

        while (seguir) {
            registro[y] = JOptionPane.showInputDialog(this, "Ingrese una modificacion: ");
            if (y == 0 && registro[y].length() == 0) {
                JOptionPane.showMessageDialog(this, "Su llave primaria no puede estar vacia");
            } else if (registro[y].length() < sizeCampo) {
                for (int k = registro[y].length(); k < sizeCampo; k++) {
                    registro[y] += "_";
                }
                seguir = false;
            } else if (registro[y].length() > sizeCampo) {
                JOptionPane.showMessageDialog(this, "El tamaño del campo es demasiado grande");
            } else {
                seguir = false;
            }
        }

        for (int i = 0; i < registro.length; i++) {
            nuevoRegistro += registro[i];
        }

        DefaultTableModel modelo = new DefaultTableModel();
        modelo = (DefaultTableModel) this.jt_addRegistroARLF.getModel();

        while (modelo.getRowCount() > 0) {
            modelo.removeRow(0);
        }

        try {
            archivoFijo.addCampo(nuevoRegistro, sizeCampo, amountCampos);
            modelo = archivoFijo.listar(modelo, sizeCampo, amountCampos);
        } catch (Exception e) {
        }
        this.jt_addRegistroARLF.setModel(modelo);
    }//GEN-LAST:event_jm_modificarActionPerformed

    private void bt_crearARLVMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_crearARLVMouseClicked
        this.jd_menuCreacion.setVisible(false);
        this.showDialog(this.jd_crearARLV);
    }//GEN-LAST:event_bt_crearARLVMouseClicked

    private void BT_CREARALRVMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BT_CREARALRVMouseClicked
        String name = "";
        name = this.tf_nombreARLV.getText();

        if (this.cb_adminCampos.getSelectedItem().toString().equals("Indicador Longitud")) {
            this.tipoAdministracionCampos = 1;
        } else if (this.cb_adminCampos.getSelectedItem().toString().equals("Delimitadores")) {
            this.tipoAdministracionCampos = 2;
        } else if (this.cb_adminCampos.getSelectedItem().toString().equals("Key Value")) {
            this.tipoAdministracionCampos = 3;
        }

        if (this.cb_adminRegistros.getSelectedItem().toString().equals("Indicador Longitud")) {
            this.tipoAdministracionRegistros = 1;
        } else if (this.cb_adminRegistros.getSelectedItem().toString().equals("Delimitadores")) {
            this.tipoAdministracionRegistros = 2;
        } else if (this.cb_adminRegistros.getSelectedItem().toString().equals("Tabla Indice")) {
            this.tipoAdministracionRegistros = 3;
        }

        archivoVariable = new ARLV(name, this.tipoAdministracionRegistros, this.tipoAdministracionCampos);
        JOptionPane.showMessageDialog(this, "Archivo creado exitosamente");
        header1 = "";
        contadorCampos = 0;
        this.tf_nombreARLV.setText(name);
        this.jd_crearARLV.setVisible(false);
        this.showDialog(this.jd_nombrarCampos2);
    }//GEN-LAST:event_BT_CREARALRVMouseClicked

    private void bt_crearHeader2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_crearHeader2MouseClicked
        header1 += this.tf_nombreHeader2.getText() + "¿";
        this.tf_nombreHeader2.setText("");
        this.contadorCampos++;
    }//GEN-LAST:event_bt_crearHeader2MouseClicked

    private void bt_saveHeaderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_saveHeaderMouseClicked
        try {
            archivoVariable.addHeader(header1, contadorCampos);
            JOptionPane.showMessageDialog(this, "Campos nombrados exitosamente");
        } catch (Exception e) {
        }
        contadorCampos = 0;
        header1 = "";
        this.jd_nombrarCampos2.setVisible(false);
    }//GEN-LAST:event_bt_saveHeaderMouseClicked

    private void jt_addRegistroARLVMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jt_addRegistroARLVMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jt_addRegistroARLVMouseClicked

    private void bt_fileChooserARLVMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_fileChooserARLVMouseClicked

    }//GEN-LAST:event_bt_fileChooserARLVMouseClicked

    private void BT_ADDREGISTROARLVMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BT_ADDREGISTROARLVMouseClicked
        int cantCampos = 0;
        int tipoAdministracionCampos = 0;
        String registroCompactado = "";
        String[] campos = new String[this.jt_addRegistroARLV.getColumnCount()];

        try {
            tipoAdministracionCampos = archivoVariable.getTipoAdministracionCampos();
            cantCampos = archivoVariable.getCantidadDeCampos();
        } catch (IOException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }

        for (int i = 0; i < cantCampos; i++) {
            campos[i] = JOptionPane.showInputDialog(this, "Ingrese un campo para su registro: ");

            //Aqui vas a ir organizando tus CAMPOS segun el metodo que te toca, cada campo es campos[i]
            //Al final cuando temines tu metodo vas a meter ese arreglo de strings en un solo string que se llama registro
            //compactado, y ese registroCompactado es el que le vas a mandar al metodo addRegistro
            if (tipoAdministracionCampos == 1) {
                //Indicadores de longitud
            } else if (tipoAdministracionCampos == 2) {
                campos[i] = campos[i] + "|";
            } else if (tipoAdministracionCampos == 3) {
                //String[] camp=archivoVariable.
            }

        }
        String registro = "";
        if (tipoAdministracionCampos == 2) {
            for (int i = 0; i < campos.length; i++) {
                registro = registro + campos[i];
            }
            registro=registro+"]";
            try {
                archivoVariable.addRegistro(registro);
            } catch (IOException ex) {
                Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        


    }//GEN-LAST:event_BT_ADDREGISTROARLVMouseClicked

    private void bt_adARLVMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_adARLVMouseClicked
        this.jd_menuAdministracion.setVisible(false);
        this.showDialog(mostrar);
    }//GEN-LAST:event_bt_adARLVMouseClicked

    public String[] enviar_nombres(String name) throws FileNotFoundException, IOException {
        RandomAccessFile archivo = new RandomAccessFile(name, "rw");
        char encontrado;
        int salir = 0;
        int salir2 = 0;
        int contador = 0;
        int contador2 = 0;
        String numero1 = "";
        String numero2 = "";
        String numeros = "";
        archivo.seek(contador);

        while (salir < 1) {
            archivo.seek(contador);
            char ver = '~';
            char ver2 = '|';

            if ((char) archivo.readByte() == ver) {

                salir++;
                archivo.seek(contador);

                while (((char) archivo.readByte()) != '^') {
                    numeros = numeros + (char) archivo.readByte();

                    contador++;
                    archivo.seek(contador);
                }
            }
            contador++;
        }
        int vab = 0;
        for (int i = 0; i < numeros.length() - 1; i++) {
            if (numeros.charAt(i) == '|') {
                vab = 1;
            } else if (vab == 0) {
                numero1 = numero1 + numeros.charAt(i);
            } else {
                numero2 = numero2 + numeros.charAt(i);
            }
        }

        char pab = 42;

        String[] campos = new String[Integer.parseInt(numero1)];
        String campo = "";
        int numero = 0;
        char letras;
        String lista = "";
        int ñ = 0;
        int con = contador - 1;
        while (ñ == 0) {
            archivo.seek(con);
            if (((char) archivo.readByte()) != '}') {
                lista = lista + ((char) archivo.readByte());

            } else {
                ñ = 1;
            }
            con++;

        }
        for (int i = 0; i < lista.length(); i++) {

            if (lista.charAt(i) == '?') {
                campos[numero] = campo;
                numero++;
                campo = "";
            } else {
                campo = campo + lista.charAt(i);
            }
        }
        sizeCampo = Integer.parseInt(numero2);
        amountCampos = Integer.parseInt(numero1);
        return campos;
    }

    public void showDialog(JDialog window) {
        window.pack();
        window.setModal(true);
        window.setLocationRelativeTo(this);
        window.setVisible(true);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BT_ADDREGISTROARLF;
    private javax.swing.JButton BT_ADDREGISTROARLV;
    private javax.swing.JButton BT_CREARALRV;
    private javax.swing.JButton bt_adARLF;
    private javax.swing.JButton bt_adARLV;
    private javax.swing.JButton bt_adminArchivos;
    private javax.swing.JButton bt_crearARLF;
    private javax.swing.JButton bt_crearARLV;
    private javax.swing.JButton bt_crearArchivo1;
    private javax.swing.JButton bt_crearArchivos;
    private javax.swing.JButton bt_crearHeader2;
    private javax.swing.JButton bt_fileChooser;
    private javax.swing.JButton bt_fileChooserARLV;
    private javax.swing.JButton bt_guardarHeader;
    private javax.swing.JButton bt_nombrarHeader;
    private javax.swing.JButton bt_saveHeader;
    private javax.swing.JComboBox cb_adminCampos;
    private javax.swing.JComboBox cb_adminRegistros;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JDialog jd_addRegistro;
    private javax.swing.JDialog jd_crearARLF;
    private javax.swing.JDialog jd_crearARLV;
    private javax.swing.JDialog jd_menuAdministracion;
    private javax.swing.JDialog jd_menuCreacion;
    private javax.swing.JDialog jd_nombrarCampos;
    private javax.swing.JDialog jd_nombrarCampos2;
    private javax.swing.JMenuItem jm_modificar;
    private javax.swing.JMenuItem jmi_eliminar;
    private javax.swing.JSpinner js_campoR1;
    private javax.swing.JSpinner js_caracteresC1;
    private javax.swing.JTable jt_addRegistroARLF;
    private javax.swing.JTable jt_addRegistroARLV;
    private javax.swing.JDialog mostrar;
    private javax.swing.JPopupMenu ppm_ARLF;
    private javax.swing.JTextField tf_nombreARLF1;
    private javax.swing.JTextField tf_nombreARLV;
    private javax.swing.JTextField tf_nombreHeader;
    private javax.swing.JTextField tf_nombreHeader2;
    // End of variables declaration//GEN-END:variables
    String nombreArchivo = "";
    int camposPorRegistro = 0;
    int caracteresPorCampo = 0;
    int contador = 0;
    ARLF archivoFijo = new ARLF();
    String header1 = "";
    int fijo = 0;
    int sizeCampo = 0;
    int amountCampos = 0;
    int tipoAdministracionRegistros = 0;
    int tipoAdministracionCampos = 0;
    int contadorCampos = 0;
    ARLV archivoVariable = new ARLV();
}
